import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@clerk/nextjs/server';
import pool from '@/lib/db';
import { GoogleGenerativeAI } from '@google/generative-ai';
import { parseNoteContent, serializeNoteContent } from '@/lib/utils/flashcardHelper';

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const { userId } = await auth();

    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Fetch current note
    const noteRes = await pool.query(
      'SELECT transcribed_text FROM public.notes WHERE id = $1 AND user_id = $2 LIMIT 1',
      [id, userId]
    );

    if (noteRes.rows.length === 0) {
      return NextResponse.json({ error: 'Catatan tidak ditemukan' }, { status: 404 });
    }

    const { textContent, mindmap, summary } = parseNoteContent(noteRes.rows[0].transcribed_text);

    if (!textContent.trim()) {
      return NextResponse.json({ error: 'Isi catatan kosong, tidak bisa membuat flashcard' }, { status: 400 });
    }

    // Call Gemini API to generate Flashcards
    const model = genAI.getGenerativeModel({ model: 'gemini-flash-lite-latest' });
    const prompt = `Anda adalah asisten edukasi ahli. Berdasarkan catatan pelajaran berikut, buatlah kumpulan 5 sampai 8 flashcards (kartu hafalan tanya jawab) yang sangat efektif untuk membantu siswa menghafal dan menguji pemahaman materi ini.
    
Format keluaran harus berupa string JSON array objek murni, tanpa pembungkus markdown block, tanpa penjelasan pembuka atau penutup. 
Contoh format output:
[
  {"q": "Pertanyaan penting 1?", "a": "Jawaban ringkas dan padat 1"},
  {"q": "Pertanyaan penting 2?", "a": "Jawaban ringkas dan padat 2"}
]

Catatan Pelajaran:
${textContent}`;

    const result = await model.generateContent(prompt);
    const resultText = result.response.text().trim();
    
    // Clean codeblock markdown wrapper if generated by AI
    let cleanedJson = resultText;
    if (cleanedJson.startsWith('```')) {
      cleanedJson = cleanedJson.replace(/^```json\s*/, '').replace(/```$/, '').trim();
    }

    // Validate JSON
    let flashcards = [];
    try {
      flashcards = JSON.parse(cleanedJson);
      if (!Array.isArray(flashcards)) {
        throw new Error('Hasil bukan array');
      }
    } catch (parseErr) {
      console.error('Gemini output invalid JSON:', resultText);
      return NextResponse.json({ error: 'Gagal membuat struktur flashcard AI' }, { status: 500 });
    }

    // Update note content by appending new flashcards
    const updatedFullText = serializeNoteContent(textContent, flashcards, mindmap, summary);

    await pool.query(
      'UPDATE public.notes SET transcribed_text = $1 WHERE id = $2 AND user_id = $3',
      [updatedFullText, id, userId]
    );

    return NextResponse.json({ success: true, flashcards });
  } catch (err: any) {
    console.error('API Flashcards Error:', err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
